import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import "./globals.css";

const figtree = Figtree({
  subsets: ["latin"],
});

const GTM_ID = process.env.NEXT_PUBLIC_GTM_ID || "";

export const metadata: Metadata = {
  title: "Breincirkel - Hersenslim",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl">
      <body className={`${figtree.className} antialiased`}>
        {children}
      </body>
      <GoogleAnalytics gaId={GTM_ID} />
    </html>
  );
}
